language: cpp
dist: bionic
sudo: required
env: CC=gcc-8 CXX=g++-8
python: "3.8"

addons:
  apt:
    sources: 
    - sourceline: 'ppa:openshot.developers/libopenshot-daily'
    packages: gcc-8 g++-8 xvfb tar cmake libopenshot-dev libopenshot-audio-dev libunittest++-dev swig doxygen doxypy libssl-dev python3 python3-dev python3-pip python3-pyqt5 python3-setuptools python3-openshot python3-pyqt5 python3-pyqt5.qtmultimedia python3-pyqt5.qtopengl python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-requests python3-xdg python3-zmq qttranslations5-l10n

install:
 - pip install --upgrade pip
 - pip install cx-Freeze==6.1

script:
  - python3 freeze.py build;
  - xvfb-run --auto-servernum --server-num=1 --server-args "-screen 0 1920x1080x24" python3 src/tests/query_tests.py

notifications:
  email: true

env:
  global:
  - TRAVIS_LIBOPENSHOT=TEST
  - LANG="en_US.UTF-8"
